import React, { useState, useEffect } from "react";
import "./Broker.css";

const BrokerForm = ({
  setShowForm,
  addBroker,
  brokerToBeUpdated,
  setBrokerToBeUpdated,
}) => {
  const [fname, setFname] = useState("");
  const [lname, setLname] = useState("");
  const [email, setEmail] = useState("");
  const [phone, setPhone] = useState("");
  const [city, setCity] = useState("");
  const [province, setProvince] = useState("");
  const [description, setDescription] = useState("");

  console.log("broker to be updated" + brokerToBeUpdated);
  useEffect(() => {
    if (brokerToBeUpdated) {
      console.log("Inside use effect");
      setFname(brokerToBeUpdated.fname);
      setLname(brokerToBeUpdated.lname);
      setEmail(brokerToBeUpdated.email);
      setPhone(brokerToBeUpdated.phone);
      setCity(brokerToBeUpdated.city);
      setProvince(brokerToBeUpdated.province);
      setDescription(brokerToBeUpdated.description);
    }
  }, [brokerToBeUpdated]);

  const descriptionLength = description.length;

  const handleFormSubmit = (e) => {
    e.preventDefault();
    // Integrate with API

    const isEmailValid = /^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$/;
    const isPhoneValid = /^\d{3}-\d{3}-\d{4}$/;
    const errors = {};

    if (
      fname === "" ||
      lname === "" ||
      email === "" ||
      phone === "" ||
      city === "" ||
      province === "" ||
      description === ""
    ) {
      errors.requiredFields = "All fields are mandatory";
    }
    if (!isEmailValid.test(email)) {
      errors.email = "Enter valid email address";
    }
    if (!isPhoneValid.test(phone)) {
      errors.phone = "Enter valid phone number (DDD-DDD-DDDD)";
    }
    if (description.length > 300) {
      errors.description = "Description must be 300 characters or less";
    }
    if (Object.keys(errors).length > 0) {
      alert("Validation errors: " + Object.values(errors).join("\n"));
      return;
    }

    const newBroker = {
      id: brokerToBeUpdated ? brokerToBeUpdated.id : Date.now().toString(), //will change this to id generated by backend
      fname: fname,
      lname: lname,
      email: email,
      phone: phone,
      city: city,
      province: province,
      description: description,
    };

    if (brokerToBeUpdated) {
      alert(JSON.stringify(newBroker, null, 2));
      setBrokerToBeUpdated(null);
    } else {
      addBroker(newBroker);
      alert("Broker Added");
    }

    setShowForm(false);
  };

  return (
    <form className="add-broker-form" onSubmit={handleFormSubmit}>
      <div className="form-contents">
        <div className="name-address">
          <div className="name">
            <input
              className="fname"
              type="text"
              value={fname}
              onChange={(e) => setFname(e.target.value)}
              placeholder="First Name"
            />

            <input
              className="lname"
              type="text"
              value={lname}
              onChange={(e) => setLname(e.target.value)}
              placeholder="Last Name"
            />
          </div>

          <div className="address">
            <input
              className="city-name"
              type="text"
              value={city}
              onChange={(e) => setCity(e.target.value)}
              placeholder="City"
            />

            <select
              className="province-name"
              value={province}
              onChange={(e) => setProvince(e.target.value)}
            >
              <option value="">Province:</option>
              <option value="Ontario">Ontario</option>
              <option value="Apartment">Quebec</option>
              <option value="Nova Scotia">Nova Scotia</option>
              <option value="Manitoba">Manitoba</option>
              <option value="British Columbia">British Columbia</option>
              <option value="Prince Edward Island">Prince Edward Island</option>
              <option value="Saskatchewan">Saskatchewan</option>
              <option value="Alberta">Alberta</option>
              <option value="Newfoundland and Labrador">
                Newfoundland and Labrador
              </option>
              <option value="Northwest Territories">
                Northwest Territories
              </option>
              <option value="Yukon">Yukon</option>
              <option value="Nunavut">Nunavut</option>
            </select>
          </div>
        </div>

        <div className="email-phone">
          <input
            className="email"
            type="text"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            placeholder="Email Address"
          />

          <input
            className="phone"
            type="text"
            value={phone}
            onChange={(e) => setPhone(e.target.value)}
            placeholder="Phone (III-III-IIII)"
          />
        </div>

        <div className="description">
          <textarea
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            placeholder="Enter Description"
          />
          <span>{300 - descriptionLength}</span>
        </div>
      </div>
      <button className="submit" type="submit">
        {brokerToBeUpdated ? "Update Broker" : "Add Broker"}
      </button>
    </form>
  );
};

export default BrokerForm;
